apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-replicationcontroller
spec:
  replicas: 2
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: xkarani-redis
          image: redis
          ports:
            - containerPort: 9090